apiVersion: v1
kind: Service
metadata:
  name: springboot-rest-demo
spec:
  type: NodePort
  selector:
    app: springboot-rest-demo
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
      nodePort: 30080
